### ISSUE TITLE
Response wait time t1 gets too high, when reading more than 8 blocks on emulated transponder

### ISSUE THREAD

**Issue by mschmitt-pf** [emsec/ChameleonMini#262]
Normally the response wait time t1 (ISO15693-3 VICC waiting time before transmitting its response after reception of an EOF from the VCD) shall be in range of 318,6µs to 323,3µs . 

But response wait time t1 (reader TX EOF to transponder TX SOF) increases significant, when reading multiple blocks with more than 8 blocks. 

Parameter to reproduce:
- emulating EM4233 transponder with uploaded tag data
- use external ISO15693 reader
- read multiple blocks (e.g. 16 blocks) of data in addressed mode
- observe response wait time t1 with scope

Note: The markers in scope plots below are not on correct position of EOF and SOF, but for relative observation I have put the markers on last reader TX pulse and first transponder modulation. The deltaT is the relevant measure.

The response wait time t1 is correct, when reading a low block count, e.g. 4 blocks. (Reader data TX = .22.23._FF.FF.AA.AA.EE.24.16.E0_.00.**03** + CRC)
![grafik](https://user-images.githubusercontent.com/65947884/82887228-00e9b780-9f48-11ea-903a-d315fc844fca.png)

Requesting 16 blocks the time t1 increases by **additional ~204µs** which is out of allowed window for t1 (Reader data TX = .22.23._FF.FF.AA.AA.EE.24.16.E0_.00.**0F** + CRC)
![grafik](https://user-images.githubusercontent.com/65947884/82887259-0cd57980-9f48-11ea-8939-29d99004e9e0.png)
![grafik](https://user-images.githubusercontent.com/65947884/82887268-0fd06a00-9f48-11ea-94a5-7a7bacab6564.png)

Many thanks in advance for your support.

**Comment by ceres-c** [comment]
Hi, being me and @MrMoDDoM the authors of that application, I'd like to say we were aware of the issue. We had not done proper tests, but were pretty sure it was a timing issue, now your issue confirms our speculations.

It was first noticed somewhere in the comments on #182 and I tried to compensate optimizing code in [be729b7](https://github.com/emsec/ChameleonMini/commit/1b38d14b2beb7970259e2821163f3f84a21424f3). It was not resolutive, but improved the situation: before it was even worse.
It'd be interesting to investigate on which part of the code is slowing down data encoding and optimize it, maybe even resorting to hand written assembly.

PS I'd like to point out this was an issue only with my ST reader, not with readers in the field

**Comment by david-oswald** [comment]
This should be resolved by PR #274 (once merged), correct @ceres-c ?

**Comment by ceres-c** [comment]
Sadly not solved.
We have been analyzing the situation and found out that both FRAM and CRC calculation is slow. No investigation went on on possible ways to improve the former, as we believed we were hitting FRAM limits (not sure on that, tough). On the other side, CRC calculation is ridiculously slow. Here you can see a capture I've just taken with my scope
![owon-fram-crc](https://user-images.githubusercontent.com/24912818/92664364-1373db00-f304-11ea-8483-21a2fe24f223.png)

- first pulse: time it took to read the data - 25,3 us
- second pulse: CRC calculation - 170 us

I'm pretty sure this delay is unjustified, so the CRC function must be improved. We have not taken the time to do so.

#274 solves other minor issues with the codec and remove useless fram reads in applications, but as stated above, this issue won't be solved like that. This is a challenge for experienced AVR asm devs

**Comment by iceman1001** [comment]
@ceres-c  , make PR to the RRG repo as well?     you moved the crc calcs.  interesting solution.

**Comment by david-oswald** [comment]
nice, well done!
